import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import Header from '@/components/Header'
import CartProvider from '@/context/CartProvider'
import { Toaster } from 'sonner'
import { ThemeProvider } from '@/context/Theme-Provider'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Clerk App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body style={inter.style} className='bg-[#f9f9fb] dark:bg-gray-800'>
          <Toaster />
          <ThemeProvider>
            <CartProvider>
              <div className='grid min-h-[100vh] grid-rows-[auto_1fr_auto]'>
                <Header />
                <main>{children}</main>
                <Footer />
              </div>
            </CartProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
